var oracoes = [
	"Senhor, dai-me força para mudar o que pode ser mudado, resignação para aceitar o que não pode ser mudado e sabedoria para distinguir uma coisa da outra.",
	"Ó Maria concebida sem pecado, rogai por nós que recorremos a vós.",
	"Jesus, manso e humilde de coração, fazei o nosso coração semelhante ao Vosso.",
	"São Miguel Arcanjo, defendei-nos no combate, sede nosso refúgio contra as maldades e ciladas do demônio. Ordene-lhe Deus, instantemente o pedimos, e vós, príncipe da milícia celeste, pela virtude divina, precipitai no inferno a Satanás e aos outros espíritos malignos que andam pelo mundo para perder as almas. Amém.", "Ó Maria concebida sem pecado, rogai por nós que recorremos a vós.",
	"Jesus, manso e humilde de coração, fazei o nosso coração semelhante ao Vosso.",
	"Ó meu Jesus, perdoai-nos, livrai-nos do fogo do inferno, levai as almas todas para o Céu e socorrei principalmente as que mais precisarem.",
	"Senhor, fazei de mim um instrumento de vossa paz. Onde houver ódio, que eu leve o amor; onde houver ofensa, que eu leve o perdão; onde houver discórdia, que eu leve a união; onde houver dúvida, que eu leve a fé; onde houver erro, que eu leve a verdade; onde houver desespero, que eu leve a esperança; onde houver tristeza, que eu leve a alegria; onde houver trevas, que eu leve a luz.",
	"Ó meu Jesus, esquecei-vos das minhas ingratidões passadas e concedei-me a graça de nunca mais pecar.",
	"Ó Maria, Mãe de Jesus e nossa Mãe, ensinai-nos a amar e a confiar em vosso Filho como vós O amastes e confiastes.",
	"Senhor Jesus Cristo, Filho do Deus vivo, tende piedade de mim, pecador.",
	"Maria, Auxílio dos Cristãos, rogai por nós.",
	"Ó Deus, que fizestes de São José um esposo fiel e um pai amoroso, concedei-nos, por sua intercessão, sermos fiéis em nossos deveres e amorosos em nossas relações.",
	"Jesus, eu confio em Vós.",
	"Ó Santíssima Trindade, eu vos adoro. Meu Deus, meu Deus, eu vos amo no Santíssimo Sacramento.",
	"Senhor, fazei-me um instrumento de vossa paz. Onde houver ódio, que eu leve o amor; onde houver ofensa, que eu leve o perdão; onde houver discórdia, que eu leve a união; onde houver dúvida, que eu leve a fé; onde houver erro, que eu leve a verdade; onde houver desespero, que eu leve a esperança; onde houver tristeza, que eu leve a alegria; onde houver trevas, que eu leve a luz.", "Santa Maria, Mãe de Deus, rogai por nós pecadores, agora e na hora da nossa morte.",
	"Pai Nosso, que estais no Céu, santificado seja o Vosso Nome, venha a nós o Vosso Reino, seja feita a Vossa vontade, assim na Terra como no Céu. O pão nosso de cada dia nos dai hoje, perdoai-nos as nossas ofensas, assim como nós perdoamos a quem nos tem ofendido, e não nos deixeis cair em tentação, mas livrai-nos do mal. Amém.",
	"Ave Maria, cheia de graça, o Senhor é convosco, bendita sois vós entre as mulheres e bendito é o fruto do vosso ventre, Jesus. Santa Maria, Mãe de Deus, rogai por nós, pecadores, agora e na hora da nossa morte. Amém.",
	"Credo: Creio em Deus Pai todo-poderoso, criador do céu e da terra. E em Jesus Cristo, seu único Filho, nosso Senhor, que foi concebido pelo poder do Espírito Santo, nasceu da Virgem Maria, padeceu sob Pôncio Pilatos, foi crucificado, morto e sepultado; desceu à mansão dos mortos, ressuscitou ao terceiro dia, subiu aos Céus, está sentado à direita de Deus Pai todo-poderoso, donde há de vir a julgar os vivos e os mortos. Creio no Espírito Santo, na Santa Igreja Católica, na comunhão dos santos, na remissão dos pecados, na ressurreição da carne, na vida eterna. Amém.",
	"Santo Anjo do Senhor, meu zeloso guardador, já que a ti me confiou a piedade divina, sempre me rege, guarda, governa e ilumina. Amém.",
	"São Miguel Arcanjo, defendei-nos no combate, sede o nosso refúgio contra as maldades e ciladas do demônio. Ordene-lhe Deus, instantemente o pedimos, e vós, príncipe da milícia celeste, pela virtude divina, precipitai no inferno a Satanás e aos outros espíritos malignos que andam pelo mundo para perder as almas. Amém.",
	"Sagrado Coração de Jesus, eu confio e espero em vós.", "Pelo Sinal da santa cruz, livrai-nos Deus Nosso Senhor dos nossos inimigos. Em nome do Pai, do Filho e do Espírito Santo, Amém.", "Glória Glória ao Pai, ao Filho e ao Espírito Santo. Assim como era no princípio, agora e sempre. Amém.", "Glória a Deus nas alturas e paz na terra aos homens por Ele amados. Senhor Deus, Rei dos céus, Deus Pai todo poderoso. Nós Vos louvamos, nós Vos bendizemos, nós Vos adoramos, nós Vos glorificamos, nós Vos damos graças por Vossa imensa glória. Senhor Jesus Cristo, Filho unigênito, Senhor Deus, Cordeiro de Deus, Filho de Deus pai, Vós que tirais os pecado do mundo, tende piedade de nós. Vós que tirais o pecado do mundo, acolhei a nossa súplica. Vós que estais à direita do Pai, tende piedade de nós. Só Vós sois Santo, só Vós, o Senhor, Só Vós o Altíssimo, Jesus Cristo, com o Espírito Santo, na glória de Deus Pai. Amém.", "Salve Rainha, Mãe de Misericórdia, vida e doçura esperança nossa salve! A vós bradamos degredados filho de Eva. A vós suspiramos gemendo e chorando neste vale de lágrimas. Eia pois advogada nossa, esses vossos olhos misericordiosos a nós volvei, e depois deste desterro, mostrai-nos Jesus, bendito fruto do vosso ventre, ó clemente, ó piedosa ó doce e sempre Virgem Maria. Rogai por nós Santa mãe de Deus, para que sejamos dignos da promessa de Cristo. Amém.", "Ó Minha Senhora. Ó Minha Mãe. Eu me ofereço inteiramente todo a Vós e em prova da minha devoção para convosco, Eu Vos consagro neste dia Os meus olhos, os meus ouvidos, a minha boca, o meu coração, E inteiramente todo o meu ser, porque assim sou vosso(a), Ó incomparável Mãe, Guardai-me, defendei-me como coisa e propriedade vossa. Amém.", "Eu vos amo, meu Deus, de todo o meu coração e sobre todas as coisas, porque sois infinitamente bom e amável, e antes quero perder tudo do que Vos ofender. Por amor de Vós, amo o meu próximo como a mim mesmo.",
];

var randomIndex = Math.floor(Math.random() * oracoes.length);
var oracao = oracoes[randomIndex];

document.getElementById("oracao").innerHTML = oracao;
